apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "workload.name" . }}
  {{- if and .Values.workload .Values.workload.annotations }}
  annotations:
    {{- toYaml .Values.workload.annotations | nindent 4 }}
  {{- end }}
  labels:
    {{- include "workload.commonLabels" . | nindent 4 }}
    {{- if and .Values.workload .Values.workload.labels }}
    {{- toYaml .Values.workload.labels | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "workload.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- if and .Values.workload .Values.workload.containers .Values.workload.containers.annotations }}
        {{- toYaml .Values.workload.containers.annotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "workload.selectorLabels" . | nindent 8 }}
        {{- if and .Values.workload .Values.workload.containers .Values.workload.containers.labels }}
        {{- toYaml .Values.workload.containers.labels | nindent 8 }}
        {{- end }}
    spec:
      containers:
        {{- range $name, $container := .Values.containers }}
        - name: {{ $name }}
          image: "{{ $container.image.name }}"
          {{- with $container.command }}
          command:
            {{- toYaml $container.command | nindent 12 }}
          {{- end }}
          {{- with $container.args }}
          args:
            {{- toYaml $container.args | nindent 12 }}
          {{- end }}
          {{- with $container.env }}
          env:
            {{- toYaml $container.env | nindent 12 }}
          {{- end }}
          {{- with $container.volumeMounts }}
          volumeMounts:
            {{- toYaml $container.volumeMounts | nindent 12 }}
          {{- end }}
          {{- with $container.livenessProbe }}
          livenessProbe:
            {{- toYaml $container.livenessProbe | nindent 12 }}
          {{- end }}
          {{- with $container.readinessProbe }}
          readinessProbe:
            {{- toYaml $container.readinessProbe | nindent 12 }}
          {{- end }}
          {{- with $container.resources }}
          resources:
            {{- toYaml $container.resources | nindent 12 }}
          {{- end }}
        {{- end }}
